name: Clang-Tidy PR Bot (TEST GitHub Runner)

permissions:
  pull-requests: write

on:
  pull_request:
    branches: master
    paths:
      - '**/*.cpp'
      - '**/*.h'

jobs:
  clang-tidy:
    runs-on: ubuntu-latest  # ← GitHub 제공 runner 

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Ensure tools are installed
      run: |
        sudo apt-get update
        sudo apt-get install -y clang-tidy bear python3

    - name: Grant execute permission to build.sh
      run: chmod +x ./build.sh

    - name: Run build with bear
      run: |
        bear -- ./build.sh

    - name: Run clang-tidy and report via reviewdog
      uses: reviewdog/action-clang-tidy@v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        reporter: github-pr-review
        fail_on_error: false
        filter_mode: diff_context
        clang_tidy_flags: '-p . -extra-arg=-std=c++98'