name: Clang-Tidy PR Bot (Markdown Comment)

on:
  pull_request:
    branches: [master]
    paths:
      - '**/*.cpp'
      - '**/*.h'

jobs:
  clang-tidy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Ensure tools are installed
      run: |
        sudo apt-get update
        sudo apt-get install -y clang-tidy bear python3

    - name: Grant execute permission to build.sh
      run: chmod +x ./build.sh

    - name: Run build with bear
      run: bear -- ./build.sh

    - name: Run clang-tidy (C++98)
      run: |
        clang-tidy -p . $(find . -name '*.cpp') -extra-arg=-std=c++98 > clang-tidy-raw.txt || true

    - name: Format output into markdown
      run: |
        python3 .github/scripts/format_tidy_report.py clang-tidy-raw.txt > clang-tidy-report.md

    - name: Comment on PR
      uses: marocchino/sticky-pull-request-comment@v2
      with:
        path: clang-tidy-report.md
